# Generated by Django 3.1.1 on 2020-11-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201117_1701'),
        ('cartview', '0002_auto_20201117_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartveiw',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_info', to='products.products'),
        ),
    ]
