# Generated by Django 3.1.1 on 2020-11-12 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressOne', models.CharField(max_length=500)),
                ('addressTwo', models.CharField(max_length=450, null=True)),
                ('city', models.CharField(blank=True, max_length=55, null=True)),
                ('phonenumber', models.CharField(max_length=15)),
                ('additionalnumber', models.CharField(max_length=15, null=True)),
                ('orderemail', models.EmailField(max_length=35, null=True, verbose_name='email')),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('orderShipped', models.BooleanField(default=False)),
                ('orderTrakingNumber', models.CharField(blank=True, max_length=550, null=True)),
                ('customerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
