# Generated by Django 3.1.1 on 2020-11-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201112_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTrakingNumber',
            field=models.CharField(blank=True, default='1031740428', editable=False, max_length=10, unique=True),
        ),
    ]
