# Generated by Django 3.1.1 on 2020-11-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20201113_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTrakingNumber',
            field=models.CharField(blank=True, default='7229734831', editable=False, max_length=10, unique=True),
        ),
    ]
