# Generated by Django 3.1.1 on 2020-11-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20201113_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTrakingNumber',
            field=models.CharField(blank=True, default='8853358848', editable=False, max_length=10, unique=True),
        ),
    ]
