# Generated by Django 3.1.1 on 2020-11-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20201113_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTrakingNumber',
            field=models.CharField(blank=True, default='1194416245', editable=False, max_length=10, unique=True),
        ),
    ]
