# Generated by Django 3.1.1 on 2020-11-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20201113_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTrakingNumber',
            field=models.CharField(blank=True, default='2302007839', editable=False, max_length=10, unique=True),
        ),
    ]
