# Generated by Django 3.1.1 on 2020-11-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20201113_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTrakingNumber',
            field=models.CharField(blank=True, default='4442126252', editable=False, max_length=10, unique=True),
        ),
    ]
