# Generated by Django 3.1.1 on 2020-11-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20201115_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTrakingNumber',
            field=models.CharField(blank=True, default='1671259637', editable=False, max_length=10, unique=True),
        ),
    ]
