# Generated by Django 3.1.1 on 2020-11-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20201115_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderTrakingNumber',
        ),
    ]
