# Generated by Django 3.1.1 on 2020-11-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsImage', '0002_auto_20201112_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='imageName',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
