# Generated by Django 3.1.1 on 2020-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsImage', '0004_auto_20201115_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='upload_products'),
        ),
    ]
