# Generated by Django 3.1.1 on 2020-11-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsImage', '0005_auto_20201115_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='upload_products/'),
        ),
    ]
