# Generated by Django 3.1.1 on 2020-11-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsImage', '0007_auto_20201115_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='upload_products/'),
        ),
    ]
