# Generated by Django 3.1.1 on 2020-11-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsImage', '0008_auto_20201116_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
