# Generated by Django 3.1.1 on 2020-11-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsImage', '0009_auto_20201116_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload_products/'),
        ),
    ]
