# Generated by Django 3.1.1 on 2020-10-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_blacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
