# Generated by Django 3.1.1 on 2020-11-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201102_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
