# Generated by Django 3.1.1 on 2020-11-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201102_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vandorName',
            field=models.CharField(max_length=350, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
