# Generated by Django 3.1.1 on 2020-11-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201102_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='vandorName',
        ),
    ]
