# Generated by Django 3.1.1 on 2020-11-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_vandorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
