# Generated by Django 3.1.1 on 2020-11-12 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201112_2107'),
        ('orderDetails', '0002_auto_20201112_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='oderID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='orders.order'),
        ),
    ]
