# Generated by Django 3.1.1 on 2020-11-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20201112_2130'),
        ('orderDetails', '0003_auto_20201112_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='oderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='orders.order'),
        ),
    ]
