# Generated by Django 3.1.1 on 2020-11-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderDetails', '0004_auto_20201112_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='oderID',
            new_name='oderid',
        ),
    ]
