# Generated by Django 3.1.1 on 2020-11-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20201113_0805'),
        ('orderDetails', '0005_auto_20201112_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='oderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
