# Generated by Django 3.1.1 on 2020-11-13 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20201113_0819'),
        ('orderDetails', '0007_auto_20201113_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='oderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='orders.order'),
        ),
    ]
