# Generated by Django 3.1.1 on 2020-11-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderDetails', '0009_auto_20201113_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='oderid',
            new_name='choices',
        ),
    ]
