# Generated by Django 3.1.1 on 2020-11-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20201113_1053'),
        ('orderDetails', '0010_auto_20201113_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='choices',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='orders.order'),
            preserve_default=False,
        ),
    ]
