# Generated by Django 3.1.1 on 2020-11-18 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201117_1701'),
        ('reviewproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_product', to='products.products'),
        ),
    ]
