# Generated by Django 3.1.1 on 2020-11-30 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_products_isrecentproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_at', models.DateTimeField(auto_now_add=True)),
                ('wishtatus', models.BooleanField(default=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wish_to_customer', to=settings.AUTH_USER_MODEL)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wish_info', to='products.products')),
            ],
        ),
    ]
