# Generated by Django 3.1.1 on 2020-11-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsCategory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productscategory',
            old_name='owner',
            new_name='ownerID',
        ),
    ]
