# Generated by Django 3.1.1 on 2020-11-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsCategory', '0002_auto_20201112_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productscategory',
            old_name='ownerID',
            new_name='vendorID',
        ),
    ]
