# Generated by Django 3.1.1 on 2020-11-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsCategory', '0003_auto_20201112_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscategory',
            name='vendorID',
        ),
    ]
