# Generated by Django 3.1.1 on 2020-09-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=350, null=True)),
                ('productPrice', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('productWeight', models.CharField(max_length=35, null=True)),
                ('productInStock', models.CharField(max_length=30, null=True)),
                ('productCoverImage', models.ImageField(null=True, upload_to='upload_productCoverImage')),
                ('productDetails', models.TextField(null=True)),
                ('productImage', models.FileField(blank=True, upload_to='')),
                ('productUpdate', models.DateTimeField(auto_now=True)),
                ('productdiscount', models.BooleanField(default=False)),
                ('isrecentproduct', models.CharField(choices=[('is_new', 'is_new'), ('not_new', 'not_new')], max_length=100)),
                ('productcategoryID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productsCategory.productscategory')),
            ],
        ),
    ]
