# Generated by Django 3.1.1 on 2020-11-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productCoverImage',
            new_name='productcoverImage',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productName',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productPrice',
            new_name='productpriceoriginal',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productWeight',
            new_name='productweight',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='owner',
            new_name='vendorID',
        ),
        migrations.RemoveField(
            model_name='products',
            name='productInStock',
        ),
        migrations.AddField(
            model_name='products',
            name='percentageofsell',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='productapprovalstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='productinstock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='productpricesell',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='productImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
