# Generated by Django 3.1.1 on 2020-11-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201112_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productImage',
        ),
    ]
