# Generated by Django 3.1.1 on 2020-11-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsCategory', '0003_auto_20201112_1638'),
        ('products', '0004_remove_products_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productcategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productsCategory.productscategory'),
        ),
    ]
