# Generated by Django 3.1.1 on 2020-11-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201116_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='percentageofsell',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='productcoverImage',
            field=models.ImageField(blank=True, null=True, upload_to='upload_productCoverImage/'),
        ),
    ]
