# Generated by Django 3.1.1 on 2020-11-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsCategory', '0003_auto_20201112_1638'),
        ('products', '0006_auto_20201117_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productcategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nested_products', to='productsCategory.productscategory'),
        ),
    ]
