# Generated by Django 3.1.1 on 2020-11-30 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201117_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='isrecentproduct',
        ),
    ]
