# Generated by Django 3.1.1 on 2020-11-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_products_isrecentproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='isrecentproduct',
            field=models.CharField(choices=[('is_new', 'is_new'), ('not_new', 'not_new')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
