# Generated by Django 3.1.1 on 2020-12-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_isrecentproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productpricesell',
            new_name='sellproductprice',
        ),
    ]
